language: python
python:
    - "2.7"
env:
    - CKANVERSION=2.8
install:
    - bash bin/travis-install-dependencies
    - pip install coveralls -U
services:
    - postgresql
    - redis
script: sh bin/travis-run-tests
after_success: coveralls
sudo: required
cache:
  directories:
    - $HOME/.cache/pip
